export default [
  "Two-Toned Boots", "Spiked Gloves", "Flanged Mace", "Crystal Belt", "Reaver Axe", "Steel Ring", "Vermillion Ring",
  "Fingerless Silk Gloves", "Bone Helmet", "Bladed Mace", "Gripped Gloves", "Leather Cap", "Opal Ring", "Wyrm Mace",
  "Prismatic Ring", "Rawhide Boots", "Marble Amulet", "Iron Greaves", "Faun's Horn", "Rawhide Tower Shield",
  "Astral Plate", "Battered Foil", "Tempered Foil", "Crusader Helmet", "Iron Circlet", "Full Scale Armour",
  "Estoc", "Carved Wand", "Opal Wand", "Cerulean Ring", "Titanium Spirit Shield", "Studded Round Shield",
  "War Buckler", "Goathide Boots", "Composite Bow", "Blinder", "Blue Pearl Amulet", "Bone Bow", "Burnished Foil",
  "Imperial Bow", "Wyrmbone Rapier", "Convoking Wand", "Vaal Mask", "Jingling Spirit Shield", "Vanguard Belt",
  "Spiraled Wand", "Gilded Buckler", "Vile Staff", "Close Helmet", "Iron Staff", "Etched Kite Shield", "Royal Bow",
  "Rock Breaker", "Painted Tower Shield", "Iron Mask", "Wrapped Boots", "Death Bow", "Velvet Gloves", "Crude Bow",
  "Battered Helm", "Ringmail Boots", "Double Claw", "Reinforced Kite Shield", "Rusted Coif", "Bone Spirit Shield",
  "Twig Spirit Shield", "Wild Leather", "Jagged Foil", "Cedar Tower Shield", "Coiled Staff", "Maple Round Shield",
  "Sabre", "Curved Blade", "Long Bow", "Driftwood Club", "Brass Maul", "Splintered Tower Shield",
  "Driftwood Spiked Shield", "Chain Boots", "Silk Slippers", "Prismatic Jewel", "Spectral Sword", "Tribal Club",
  "Iron Sceptre", "Varnished Coat", "Onyx Amulet", "Thorn Rapier", "Bronze Gauntlets", "Lathi", "Plague Mask",
  "Short Bow", "Wool Gloves", "Profane Wand", "Reaver Sword", "Shadow Axe", "Morning Star", "Leather Belt",
  "Redwood Spiked Shield", "Decorative Axe", "Pagan Wand", "Scarlet Raiment", "Citrine Amulet", "Turquoise Amulet",
  "Hubris Circlet", "Reinforced Tower Shield", "Arming Axe", "Tarnished Spirit Shield", "Ironscale Boots",
  "Variscite Blade", "War Plate", "Jagged Maul", "Sallet", "Full Leather", "Ringmail Coat", "Ceremonial Mace",
  "Agate Amulet", "Ivory Spirit Shield", "Jade Amulet", "Lithe Blade", "War Hammer", "Prophecy Wand", "Pine Buckler",
  "Wrist Chopper", "Corroded Tower Shield", "Long Staff", "Double Axe", "Totemic Maul", "Amber Amulet", "Lapis Amulet",
  "Thicket Bow", "Ezomyte Dagger", "Blunt Arrow Quiver", "Infantry Brigandine", "Plated Gauntlets",
  "Cardinal Round Shield", "Vine Circlet", "Coral Amulet", "Gold Amulet", "Scholar Boots", "Two-Stone Ring",
  "Paua Amulet", "Visored Sallet", "Flaying Knife", "Nubuck Gloves", "Vaal Regalia", "Recurve Bow", "Buckskin Tunic",
  "Scale Doublet", "Wraith Sword", "Elegant Foil", "Gilded Sallet", "Heavy Belt", "Elegant Sword", "Wrapped Mitts",
  "Diamond Ring", "Eclipse Staff", "Sun Leather", "Steel Greaves", "Boot Blade", "Strapped Mitts", "Void Sceptre",
  "Two-Handed Sword", "Rawhide Gloves", "Opal Sceptre", "Soldier Helmet", "Quartz Wand", "Solar Maul", "Horned Sceptre",
  "Timeworn Claw", "Leather Hood", "Nubuck Boots", "Chain Gloves", "Sorcerer Boots", "Jewelled Foil",
  "Embroidered Gloves", "Pernarch", "Dream Mace", "Grinning Fetish", "Ironscale Gauntlets", "Full Ringmail",
  "Bronze Sceptre", "Blood Sceptre", "Timber Axe", "Decurve Bow", "Royal Staff", "Chainmail Vest", "Copper Plate",
  "Driftwood Wand", "Tornado Wand", "Ezomyte Axe", "Imp Dagger", "Boot Knife", "Jasper Axe", "Buckskin Tower Shield",
  "Layered Kite Shield", "Crimson Round Shield", "Brass Spirit Shield", "Grappler", "Battle Hammer", "Ochre Sceptre",
  "Throat Stabber", "Reinforced Greaves", "Butcher Axe", "Barbed Club", "Cone Helmet", "Imperial Claw",
  "Spike-Point Arrow Quiver", "Coronal Maul", "Goathide Gloves", "Broad Sword", "Chainmail Tunic", "Iron Gauntlets",
  "Piledriver", "Spiny Maul", "Ezomyte Tower Shield", "Torture Cage", "Tricorne", "Crescent Staff", "Lion Sword",
  "Sekhem", "Sparkling Claw", "Ebony Tower Shield", "Prehistoric Claw", "Hammered Buckler", "Ancient Sword",
  "Heathen Wand", "Engraved Hatchet", "Iron Hat", "Silken Garb", "Serpentine Staff", "Prong Dagger", "Quartz Sceptre",
  "Sapphire Ring", "Vaal Buckler", "Highland Blade", "Copper Kris", "Sundering Axe", "Bronzescale Gauntlets",
  "Soldier's Brigandine", "Steel Kite Shield", "Lion Pelt", "Walnut Spirit Shield", "Cat's Paw",
  "Chiming Spirit Shield", "Steelscale Gauntlets", "Hook Sword", "Colossal Tower Shield", "Imbued Wand",
  "Archon Kite Shield", "Sorcerer Gloves", "Thief's Garb", "Eelskin Tunic", "Copper Tower Shield",
  "Scarlet Round Shield", "Fright Maul", "Smallsword", "Ringmail Gloves", "Champion Kite Shield", "Painted Buckler",
  "Fishscale Gauntlets", "Primitive Staff", "Broad Axe", "Silk Gloves", "Tribal Circlet", "Lacquered Buckler",
  "Crested Tower Shield", "Oak Buckler", "Silken Hood", "Platinum Kris", "Ceremonial Kite Shield", "Ruby Ring",
  "Ambusher", "Dusk Blade", "Sharktooth Arrow Quiver", "Riveted Boots", "Foul Staff", "Full Plate", "Military Staff",
  "Golden Kris", "Splendid Round Shield", "Zodiac Leather", "Royal Burgonet", "Sage's Robe", "Spiked Round Shield",
  "Headsman Axe", "Chainmail Doublet", "Alloyed Spiked Shield", "Padded Jacket", "Murder Boots", "Topaz Ring",
  "Full Chainmail", "Yew Spirit Shield", "Trisula", "Plated Maul", "Searching Eye Jewel", "Slink Boots", "Fright Claw",
  "Woodful Staff", "Silk Robe", "Thresher Claw", "Steelhead", "Stiletto", "Festival Mask", "Antique Rapier",
  "Bronze Tower Shield", "Ornate Spiked Shield", "Mesh Gloves", "Butcher Sword", "Legion Hammer", "Ritual Sceptre",
  "Leatherscale Boots", "Ornate Sword", "Bone Armour", "Steelscale Boots", "Vaal Hatchet", "Chain Hauberk",
  "Unset Ring", "Coral Ring", "Eternal Burgonet", "Cutlass", "Imperial Skean", "Barbute Helmet", "Exquisite Blade",
  "Bronzescale Boots", "Reflex Bow", "Spectral Axe", "Mesh Boots", "Deerskin Gloves", "Butcher Knife", "Etched Hatchet",
  "Lunaris Circlet", "Carving Knife", "Boarding Axe", "Light Brigandine", "Scholar's Robe", "Pinnacle Tower Shield",
  "Holy Chainmail", "Trapper Boots", "Ghastly Eye Jewel", "Cabalist Regalia", "Lead Sceptre", "Stygian Vise",
  "Latticed Ringmail", "Behemoth Mace", "Gavel", "Sage Wand", "Ancient Spirit Shield", "Velvet Slippers",
  "Harmonic Spirit Shield", "Petrified Club", "Wyrmscale Doublet", "Skean", "Murderous Eye Jewel", "Bone Circlet",
  "Tomahawk", "Colossus Mallet", "Deicide Mask", "Grove Bow", "Engraved Wand", "Clasped Boots", "Great Mallet",
  "Lacewood Spirit Shield", "Zealot Boots", "Titan Greaves", "Imperial Buckler", "Harbinger Bow", "Noble Axe",
  "Moon Staff", "Hussar Brigandine", "Wool Shoes", "Strapped Boots", "Dagger Axe", "Scare Mask", "Field Lamellar",
  "Bastard Sword", "Iron Ring", "Gladiator Helmet", "Quarterstaff", "Sadist Garb", "Fossilised Spirit Shield",
  "Poignard", "Compound Spiked Shield", "Crusader Buckler", "Two-Point Arrow Quiver", "Assassin Bow", "Eelskin Gloves",
  "Rusted Spike", "Shackled Boots", "Infernal Sword", "Great Helmet", "Phantom Mace", "Compound Bow", "Golden Mask",
  "Goat's Horn", "Crystal Wand", "Steel Gauntlets", "Vaal Gauntlets", "Serpentscale Boots", "Shadow Sceptre",
  "Sniper Bow", "Crimson Raiment", "Cleaver", "Crusader Chainmail", "Prophet Crown", "Glorious Leather",
  "Steelwood Bow", "Mahogany Tower Shield", "Clasped Mitts", "Teak Round Shield", "Mosaic Kite Shield", "Stag Sceptre",
  "Broadhead Arrow Quiver", "Penetrating Arrow Quiver", "Sambar Sceptre", "Moonstone Ring", "Angelic Kite Shield",
  "Battle Sword", "Titan Gauntlets", "Demon's Horn", "Gemini Claw", "Corrugated Buckler", "Battle Buckler",
  "Dragonscale Gauntlets", "Omen Wand", "Baselard", "Elegant Round Shield", "Hypnotic Eye Jewel", "Ornate Ringmail",
  "Trapper Mitts", "Highborn Bow", "Praetor Crown", "Assassin's Garb", "Slink Gloves", "Serpent Wand", "Tiger's Paw",
  "Golden Buckler", "Frontier Leather", "Battle Plate", "Quilted Jacket", "Wolf Pelt", "Arena Plate", "Deerskin Boots",
  "Lordly Plate", "Mage's Vestment", "Waxed Garb", "Spiked Bundle", "Gilded Axe", "Jade Chopper", "Oiled Coat",
  "Longsword", "Spiked Club", "Sinner Tricorne", "Vaal Spirit Shield", "Vaal Greatsword", "Soldier Gloves",
  "Arcanist Gloves", "Labrys", "Enameled Buckler", "Dragoon Sword", "Ivory Bow", "Wyrmscale Boots", "Riveted Gloves",
  "Carnal Armour", "Plated Greaves", "Stealth Gloves", "Tiger Hook", "Ezomyte Burgonet", "Amethyst Ring",
  "Glorious Plate", "Samite Gloves", "Imperial Maul", "Jasper Chopper", "Talon Axe", "Spiny Round Shield",
  "Soldier Boots", "Raven Mask", "Gut Ripper", "Crystal Sceptre", "Ezomyte Spiked Shield", "Burnished Spiked Shield",
  "Twin Claw", "Footman Sword", "Polished Spiked Shield", "Hunter Hood", "Tiger Sword", "Aventail Helmet",
  "Pecoraro", "Platinum Sceptre", "Conjurer's Vestment", "Satin Gloves", "Fencer Helm", "Sledgehammer",
  "Mirrored Spiked Shield", "Vaal Blade", "Ambush Mitts", "Arcanist Slippers", "Paua Ring", "Despot Axe",
  "Conjurer Gloves", "Carnal Mitts", "Ranger Bow", "Baroque Round Shield", "Silken Wrap", "Judgement Staff",
  "Ironwood Buckler", "Bronze Plate", "Ezomyte Blade", "Twilight Blade", "Occultist's Vestment", "Meatgrinder",
  "Lacquered Helmet", "Murder Mitts", "Gouger", "Royal Axe", "Sharkskin Gloves", "Vaal Sceptre", "Vaal Greaves",
  "Ornate Mace", "Crusader Gloves", "Maraketh Bow", "Antique Gauntlets", "Gladius", "War Axe", "Courtesan Sword",
  "Secutor Helm", "Sovereign Spiked Shield", "Sleek Coat", "Girded Tower Shield", "Carnal Sceptre", "Dragon Mace",
  "Satin Slippers", "Mallet", "Reaver Helmet", "Serpentscale Gauntlets", "Ceremonial Axe", "Spine Bow",
  "Wyrmscale Gauntlets", "War Sword", "Headman's Sword", "Nailed Fist", "Copper Sword", "Imperial Staff",
  "Runic Hatchet", "Mind Cage", "Terror Claw", "Rustic Sash", "Ezomyte Staff", "Callous Mask", "Decimation Bow",
  "Supreme Spiked Shield", "Antique Greaves", "Maelström Staff", "Eelskin Boots", "Saintly Chainmail",
  "Spidersilk Robe", "Sharkskin Boots", "Ambush Boots", "Serrated Arrow Quiver", "Primeval Rapier", "Zealot Gloves",
  "Viridian Jewel", "Ancient Gauntlets", "Samite Helmet", "Cobalt Jewel", "Wraith Axe", "Gold Ring", "Samite Slippers",
  "Hydrascale Gauntlets", "Nightmare Bascinet", "Solaris Circlet", "Goliath Gauntlets", "Corsair Sword", "Vaal Axe",
  "Abyssal Sceptre", "Gladiator Plate", "Karui Sceptre", "Karui Axe", "Ursine Pelt", "Saint's Hauberk", "Cloth Belt",
  "Shagreen Gloves", "Great Crown", "Shagreen Boots", "Magistrate Crown", "Harpy Rapier", "Fancy Foil", "Royal Skean",
  "Necromancer Circlet", "Highborn Staff", "Exquisite Leather", "Harlequin Mask", "Noble Tricorne", "Regicide Mask",
  "Fiend Dagger", "Demon Dagger", "Royal Sceptre", "Ancient Greaves", "Pig-Faced Bascinet", "Crusader Plate",
  "Dragonscale Boots", "Carnal Boots", "Eye Gouger", "Assassin's Mitts", "Thorium Spirit Shield", "Midnight Blade",
  "Zealot Helmet", "Chain Belt", "Legion Gloves", "Sun Plate", "Fluted Bascinet", "Goliath Greaves", "Vaal Rapier",
  "Terror Maul", "Vaal Claw", "Hydrascale Boots", "Fleshripper", "Siege Helmet", "Blood Raiment", "Conjurer Boots",
  "Steel Circlet", "Sai", "Crusader Boots", "Noble Claw", "Shagreen Tower Shield", "Triumphant Lamellar", "Auric Mace",
  "Fire Arrow Quiver", "Laminated Kite Shield", "Spiraled Foil", "Lacquered Garb", "Tenderizer", "Karui Chopper",
  "Elegant Ringmail", "General's Brigandine", "Assassin's Boots", "Hellion's Paw", "Conquest Chainmail",
  "Chest Splitter", "Serrated Foil", "Branded Kite Shield", "Stealth Boots", "Dread Maul", "Commander's Brigandine",
  "Legion Sword", "Karui Maul", "Graceful Sword", "Coronal Leather", "Whalebone Rapier", "Awl", "Etched Greatsword",
  "Woodsplitter", "Desert Brigandine", "Sharkskin Tunic", "Full Dragonscale", "Sentinel Jacket", "Full Wyrmscale",
  "Elder Sword", "Widowsilk Robe", "Nightmare Mace", "Tyrant's Sekhem", "Cutthroat's Garb", "Crimson Jewel",
  "Abyssal Axe", "Loricated Ringmail", "Citadel Bow", "Devout Chainmail", "Colosseum Plate", "Primordial Staff",
  "Slaughter Knife", "Infernal Axe", "Golden Plate", "Studded Belt", "Eagle Claw", "Gutting Knife", "Destiny Leather",
  "Engraved Greatsword", "Legion Boots", "Majestic Plate", "Apex Rapier", "Destroyer Regalia", "Eternal Sword",
  "Battle Lamellar", "Gemstone Sword", "Alder Spiked Shield", "Savant's Robe", "Siege Axe", "Ancestral Club",
  "Crypt Armour", "Void Axe", "Great White Claw", "Dragonbone Rapier", "Necromancer Silks"
]