export default [
  "Lacquered", "Studded", "Ribbed", "Fortified", "Plated", "Essences", "Carapaced", "Encased", "Enveloped",
  "Supple", "Pliant", "Flexible", "Upgraded", "Durable", "Sturdy", "Resilient", "Reinforced", "Layered",
  "Lobstered", "Buttressed", "Thickened", "Girded", "Impregnable", "Impenetrable", "Reinforcing",
  "Reliable", "Unfailing", "Oyster's", "Urchin's", "Nautilus's", "Crocodile's", "Chosen", "Beetle's",
  "Crab's", "Armadillo's", "Rhino's", "Elephant's", "Mammoth's", "Coelacanth's", "Swordfish's", "Shark's",
  "Whale's", "Rhoa's", "Rhex's", "Chimeral's", "Bull's", "Frosted", "Chilled", "Icy", "Frigid", "Freezing",
  "Frozen", "Glaciated", "Polar", "Entombing", "Crystalising", "Heated", "Smouldering", "Smoking",
  "Burning", "Flaming", "Scorching", "Incinerating", "Blasting", "Cremating", "Carbonising", "Humming",
  "Buzzing", "Snapping", "Crackling", "Sparking", "Arcing", "Shocking", "Discharging", "Electrocuting",
  "Vapourising", "Corrupting", "Glinting", "Burnished", "Polished", "Honed", "Gleaming", "Annealed",
  "Razor-sharp", "Tempered", "Flaring", "Malicious", "Heavy", "Serrated", "Wicked", "Vicious",
  "Bloodthirsty", "Cruel", "Tyrannical", "Merciless", "Subterranean", "Squire's", "Journeyman's",
  "Reaver's", "Mercenary's", "Champion's", "Conqueror's", "Emperor's", "Dictator's", "Shining",
  "Glimmering", "Glowing", "Glittering", "Radiating", "Pulsing", "Seething", "Blazing",
  "Scintillating", "Incandescent", "Resplendent", "Dazzling", "Will-o-wisp's", "Nymph's", "Sylph's",
  "Cherub's", "Spirit's", "Eidolon's", "Blessed", "Anointed", "Sanctified", "Hallowed", "Beatified",
  "Consecrated", "Protective", "Strong-Willed", "Resolute", "Fearless", "Dauntless", "Indomitable",
  "Unassailable", "Unfaltering", "The Shaper's", "Hasty", "Monk's", "Prior's", "Abbot's", "Exarch's",
  "Acolyte's", "Deacon's", "Priest's", "Bishop's", "Pixie's", "Gremlin's", "Boggart's", "Naga's",
  "Djinn's", "Seraphim's", "Agile", "Dancer's", "Acrobat's", "Fleet", "Blurred", "Phased", "Vaporous",
  "Blurring", "Shade's", "Ghost's", "Spectre's", "Wraith's", "Phantasm's", "Nightmare's", "Mirage's",
  "Illusion's", "Flea's", "Fawn's", "Ram's", "Ibex's", "Mosquito's", "Moth's", "Butterfly's", "Wasp's",
  "Dragonfly's", "Hummingbird's", "Vulture's", "Kingfisher's", "Owl's", "Eagle's", "Perpetual",
  "Chemist's", "Ample", "Saturated", "Concentrated", "Cautious", "Alchemist's", "Experimenter's",
  "Enduring", "Flagellant's", "Sapping", "Foreboding", "Caustic", "Panicked", "Bubbling", "Catalysed",
  "Surgeon's", "Avenger's", "Recovering", "Inspiring", "Mad Lord's", "Splintermind's", "Frost Singer's",
  "Winter Beckoner's", "Flame Shaper's", "Lava Conjurer's", "Thunderhand's", "Tempest Master's",
  "Fletcher's", "Sharpshooter's", "Nihilist's", "Anarchist's", "Frost Weaver's", "Winterbringer's",
  "Flame Spinner's", "Lava Caller's", "Exemplary", "Paragon's", "Quintessential", "Flawless",
  "Thunder Lord's", "Tempest King's", "Combatant's", "Weaponmaster's", "Citaqualotl's", "Reanimator's",
  "Summoner's", "Necromancer's", "Competitor's", "Matatl's", "Martinet's", "Lithomancer's", "Tecton's",
  "Magister's", "Infixed", "Ingrained", "Instilled", "Infused", "Inculcated", "Interpolated", "Inspired",
  "Interpermeated", "Scrapper's", "Brawler's", "Fencer's", "Gladiator's", "Duelist's", "Hero's",
  "Legend's", "Victor's", "Shadowy", "Ethereal", "Unworldly", "Ephemeral", "Evanescent", "Unreal",
  "Incorporeal", "Illusory", "Magpie's", "Pirate's", "Dragon's", "Perandus'", "Deflecting", "Flanking",
  "Harmonic", "Charging", "Cleaving", "Sinister", "Parrying", "Volleying", "Fierce", "Cryomantic",
  "Pyromantic", "Electromantic", "Resonant", "Warding", "Wright's", "Chaotic", "Ripping", "Savage",
  "Avalanching", "Arctic", "Chilling", "Technical", "Slicing", "Lethal", "Soldier's", "Serene", "Fevered",
  "Evasive", "Infernal", "Puncturing", "Thundering", "Surging", "Beating", "Brutal", "Energetic",
  "Shimmering", "Vivid", "Enlightened", "Sabotage", "Arming", "Leadership", "Master's", "Bandit's",
  "Harming", "Piercing", "Sharpened", "Armoured", "Shielding", "Thwarting", "Dissipating", "Halting",
  "Sorcerer's", "Battlemage's", "Wizard's", "Blunt", "Judging", "Fencing", "Shaman's", "Carved",
  "Trapping", "Warrior's", "Sundering", "Rupturing", "Jinxing", "Hale", "Healthy", "Sanguine",
  "Stalwart", "Stout", "Robust", "Rotund", "Virile", "Athlete's", "Fecund", "Vigorous", "Rapturous",
  "Prime", "Eldritch", "Remora's", "Lamprey's", "Vampire's", "Youthful", "Spirited", "Vivacious",
  "Beryl", "Cobalt", "Azure", "Sapphire", "Cerulean", "Aqua", "Opalescent", "Gentian", "Chalybeous",
  "Mazarine", "Blue", "Zaffre", "Ultramarine", "Thirsty", "Parched", "Runner's", "Sprinter's",
  "Stallion's", "Gazelle's", "Jogger's", "Cheetah's", "Hellion's", "Caster's", "Conjuror's",
  "Warlock's", "Mage's", "Archmage's", "Lich's", "Apprentice's", "Adept's", "Scholar's", "Professor's",
  "Occultist's", "Incanter's", "Essence's", "Glyphic", "Runic", "Bitter", "Biting", "Alpine", "Snowy",
  "Hailing", "Crystalline", "Cryomancer's", "Tul's", "Searing", "Sizzling", "Blistering", "Cauterising",
  "Volcanic", "Magmatic", "Pyroclastic", "Xoph's", "Charged", "Hissing", "Bolting", "Coursing", "Striking",
  "Smiting", "Ionising", "Esh's", "Chanter's", "Thaumaturgist's", "Essence", "Catalysing", "Infusing",
  "Catalyzing", "Empowering", "Unleashed", "Overpowering", "Devastating",

  "of Steadiness", "of Calm", "of Accuracy", "of Precision", "of Craft", "of the Sniper",
  "of the Marksman", "of the Deadeye", "of the Ranger", "of the Assassin", "of the Essence",
  "of Lioneye", "of Shining", "of Light", "of Radiance", "of the Underground", "of Skill",
  "of Ease", "of Mastery", "of Grandmastery", "of the Elder", "of Renown", "of Acclaim",
  "of Fame", "of Infamy", "of Celebration", "of the Clouds", "of the Sky", "of the Meteor",
  "of the Comet", "of the Heavens", "of the Galaxy", "of the Universe", "of the Infinite",
  "of the Multiverse", "of the Mongoose", "of the Lynx", "of the Fox", "of the Falcon",
  "of the Panther", "of the Leopard", "of the Jaguar", "of the Phantom", "of the Wind",
  "of the Blur", "of the Pupil", "of the Student", "of the Prodigy", "of the Augur",
  "of the Philosopher", "of the Sage", "of the Savant", "of the Virtuoso", "of the Genius",
  "of the Polymath", "of the Brute", "of the Wrestler", "of the Bear", "of the Lion",
  "of the Gorilla", "of the Goliath", "of the Leviathan", "of the Titan", "of the Gods",
  "of the Godslayer", "of Talent", "of Nimbleness", "of Expertise", "of Legerdemain",
  "of Prestidigitation", "of Sortilege", "of Finesse", "of Ire", "of Anger", "of Rage",
  "of Fury", "of Ferocity", "of Destruction", "of Needling", "of Stinging", "of Piercing",
  "of Puncturing", "of Rupturing", "of Penetrating", "of Shaping", "of Incision", "of Rending",
  "of Menace", "of Havoc", "of Disaster", "of Calamity", "of Ruin", "of Unmaking", "of Snow",
  "of Sleet", "of Ice", "of Rime", "of Floe", "of Glaciation", "of Embers", "of Coals",
  "of Cinders", "of Flames", "of Immolation", "of Ashes", "of Sparks", "of Static",
  "of Electricity", "of Voltage", "of Discharge", "of Arcing", "of Fearlessness",
  "of Blurring", "of Fending", "of Iron Skin", "of Acceleration", "of Staunching",
  "of Quickening", "of Infliction", "of Heat", "of Warding", "of Draining", "of Reflexes",
  "of Dousing", "of Bloodletting", "of Gluttony", "of Craving", "of Animation",
  "of Adrenaline", "of Curing", "of Resistance", "of Grounding", "of Refilling",
  "of Overflowing", "of Sipping", "of Savouring", "of Plunder", "of Raiding", "of Archaeology",
  "of Excavation", "of Deadliness", "of Adaption", "of Dexterity", "of Cunning",
  "of Intelligence", "of Strength", "of Athletics", "of Spirit", "of Blasting", "of Zeal",
  "of Berserking", "of Enchanting", "of Freezing", "of Burning", "of Poisoning", "of Shocking",
  "of Order", "of the Beast", "of Potency", "of the Dragon", "of Rejuvenation", "of Efficiency",
  "of Venom", "of Soaring", "of Stunning", "of Recovery", "of Haemophilia", "of Bleeding",
  "of Combusting", "of Shelter", "of Wounding", "of Entropy", "of the Apocalypse",
  "of the Elements", "of Focus", "of the Hearth", "of Insulation", "of Absorption", "of Weight",
  "of Combat", "of Demolishing", "of Command", "of Suggestion", "of Instruction", "of Training",
  "of the Wall", "of Acclimatisation", "of Resilience", "of Fortitude", "of Archery",
  "of Annihilation", "of Mysticism", "of Runes", "of Restoration", "of Regrowth",
  "of Nourishment", "of Success", "of Victory", "of Triumph", "of the Newt", "of the Lizard",
  "of the Flatworm", "of the Starfish", "of the Hydra", "of the Troll", "of Ryslatha",
  "of the Phoenix", "of the Order", "of Youthfulness", "of Vitality", "of Longevity",
  "of Immortality", "of Osmosis", "of Consumption", "of Excitement", "of Joy", "of Elation",
  "of Bliss", "of Euphoria", "of Nirvana", "of Darting", "of Flight", "of Propulsion",
  "of the Zephyr", "of the Gale", "of the Worthy", "of the Apt", "of the Lost", "of Banishment",
  "of Eviction", "of Expulsion", "of Exile", "of Bameth", "of the Inuit", "of the Seal",
  "of the Penguin", "of the Yeti", "of the Walrus", "of the Polar Bear", "of the Ice",
  "of Haast", "of the Whelpling", "of the Salamander", "of the Drake", "of the Kiln",
  "of the Furnace", "of the Volcano", "of the Magma", "of Tzteosh", "of the Cloud",
  "of the Squall", "of the Storm", "of the Thunderhead", "of the Tempest", "of the Maelstrom",
  "of the Lightning", "of Ephij", "of the Crystal", "of the Prism", "of the Kaleidoscope",
  "of Variegation", "of the Rainbow", "of the Span", "of the Thundersnow", "of the Chimaera",
  "of the Ashcloud", "of Intercepting", "of Walling", "of Blocking", "of Impact", "of Dazing",
  "of Slamming", "of Staggering", "of the Pugilist", "of the Brawler", "of the Boxer",
  "of the Combatant", "of the Gladiator", "of Thick Skin", "of Stone Skin", "of Steel Skin",
  "of Adamantite Skin", "of Corundum Skin"
]
